/* This file was generated by scm2c from source file "db.scm" */
/*  "db.scm" WB-tree File Based Associative String Data Base System. */
/*  Copyright (C) 1991, 1992, 1993, 2000, 2010 Free Software Foundation, Inc. */
/*  */
/*  This program is free software: you can redistribute it and/or modify */
/*  it under the terms of the GNU Lesser General Public License as */
/*  published by the Free Software Foundation, either version 3 of the */
/*  License, or (at your option) any later version. */
/*  */
/*  This program is distributed in the hope that it will be useful, but */
/*  WITHOUT ANY WARRANTY; without even the implied warranty of */
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU */
/*  Lesser General Public License for more details. */
/*  */
/*  You should have received a copy of the GNU Lesser General Public */
/*  License along with this program.  If not, see */
/*  <http://www.gnu.org/licenses/>. */

/*  Advertised Java and C# API */


#include "wbsys.h"


HAND *create_bt(SEGD *seg,int typ,int wcb)
{
  {
    HAND *a_han = make_hand();
    int ans = bt_create(seg, typ, a_han, wcb);
    if (err_P(ans))
      return 0;
    else return a_han;
  }
}


HAND *open_bt(SEGD *seg,long blknum,int wcb)
{
  {
    HAND *a_han = make_hand();
    int ans = bt_open(seg, blknum, a_han, wcb);
    if (err_P(ans))
      return 0;
    else return a_han;
  }
}


void close_bt(HAND *han)
{
  bt_close(han);
  free(han);
  return;
}


HAND *create_db(SEGD *seg,int typ,unsigned char *name_str)
{
  unsigned char tmp_str[0x100];
  HAND *a_han = create_bt(seg, typ, 0);
  HAND *d_han = open_bt(seg, 1, (wcb_sap)+(wcb_sar));
  if ((!(a_han))
      || (!(d_han)))
    return 0;
  else {
    long2str(tmp_str, 1, han_id(a_han));
    tmp_str[0] = 4;
    bt_put(d_han, name_str, sizeof(name_str)-1, tmp_str, 5);
    close_bt(d_han);
    return a_han;
  }
}


HAND *open_db(SEGD *seg,unsigned char *name_str)
{
  unsigned char tmp_str[0x100];
  HAND *d_han = open_bt(seg, 1, (wcb_sap)+(wcb_sar));
  if (!(d_han))
    return 0;
  else {
    int tlen = bt_get(d_han, name_str, sizeof(name_str)-1, tmp_str);
    close_bt(d_han);
    if (err_P(tlen))
      return 0;
    else if ((tlen)==5)
      return open_bt(seg, str2long(tmp_str, 1), 0);
    else return 0;
  }
}


int flush_ents(int attempts,int k)
{
  return ents_flush(attempts, k);
}
