/* This file was generated by scm2c from source file "db.scm" */

HAND *create_bt(SEGD *seg,int typ,int wcb);

HAND *open_bt(SEGD *seg,long blknum,int wcb);

void close_bt(HAND *han);

HAND *create_db(SEGD *seg,int typ,unsigned char *name_str);

HAND *open_db(SEGD *seg,unsigned char *name_str);

int flush_ents(int attempts,int k);
