(					; -*-scheme-*-
 (*namespace-id* "wb")
 (*class-name* "wb")
 (*cs-dir* "csharp/")
 (*cs-output-file-name* "Wb.cs")
 (*use-list* ("System"
	      "System.IO"
	      "System.Threading"
	      "System.Text"
	      "System.Reflection"
	      "System.Collections"))
 ("*-ct"  int                 )
 ("*-id"  int                 )
 ("caller" "String"	      )
 ("*ame"  "String"            )
 ("*ara"  array               )
 ("*blk"  (array byte)        )
 ("*buk"  "Ent"               )
 ("*ent"  "Ent"               )
 ("*fct"  int                 )
 ("*fun"  (function int)      )
 ("*han"  "wb.Han"            )
 ("*ind"  "Ent"               )
 ("*lck"  "Lck"               )
 ("*ait"  "Ent"               )
 ("*nts"  "Ent"               )
 ("*num"  int                 )
 ("*ong"  int                 )
 ("*pkt"  (array int)         )
 ("*str[0-9]" (array byte)    )
 ("*str"  (array byte)        )
 ("key"  (array byte)        )
 ("*byts" (array byte)        )
 ("*tab"  array               )
 ("*bck"  bool                )
 ("*blk-free" bool            )
 ("*chain-put" bool           )
 ("*unc"  (function int)      )
 ("file-position" bool        )
 ("blkio:*" bool              )
 ("*ile"  "FileStream"        )
 ("seg-chain"  "wb.Seg")
 ("*seg"  "wb.Seg")
 ("*segd"  "wb.Seg")
 ("close-seg*" int)
 ("reason" "String")
 ("blk:*" bool)
 ("parent-insert-update" bool)
 ("bt-open-new" bool)
 ("ents:*" bool)
 ("*ent-copy" bool)
 ("flush-ents"	int)
 ("*-bt"	"Han")
 ("*-db"	"Han")
 ("bt:*"	(array byte))
 ("bt:del"	bool)
 ("bt:delete"	int)
 ("bt:insert"	bool)
 )
