(					; -*-scheme-*-
 (*package-name* "wb")
 ("*-ct"  int                )
 ("*-id"  int                )
 ("caller" "String"	      )
 ("*ame"  "String"            )
 ("*ara"  array               )
 ("*blk"  (array byte)        )
 ("*buk"  "Ent"               )
 ("*ent"  "Ent"               )
 ("*fct"  int                 )
 ("*fun"  (function int)      )
 ("*han"  "Han"               )
 ("*ind"  "Ent"               )
 ("*lck"  "Lck"               )
 ("*ait"  "Ent"               )
 ("*nts"  "Ent"               )
 ("*num"  int                 )
 ("*ong"  int                 )
 ("*pkt"  (array int)         )
 ("*str[0-9]" (array byte)    )
 ("*str"  (array byte)        )
 ("key"  (array byte)        )
 ("*byts" (array byte)        )
 ("*tab"  array               )
 ("*bck"  bool             )
 ("*blk-free" bool         )
 ("*chain-put" bool        )
 ("*unc"  (function int)      )
 ("file-position" bool     )
 ("blkio:*" bool           )
 ("*ile"  "java.io.RandomAccessFile")
 ("seg-chain"  "Seg")
 ("*seg"  "Seg")
 ("*segd"  "Seg")
 ("close-seg*" int)
 ("reason" "String")
 ("blk:*" bool)
 ("parent-insert-update" bool)
 ("bt-open-new" bool)
 ("ents:*" bool)
 ("*ent-copy" bool)
 ("flush-ents"	int)
 ("*-bt"	"Han")
 ("*-db"	"Han")
 ("bt:*"	(array byte))
 ("bt:del"	bool)
 ("bt:delete"	int)
 ("bt:insert"	bool)
 )
